import express from 'express';
import * as adminCtrl from '../controllers/admin.controller';
import isAuthenticated from '../middlewares/authenticate';
import validate from '../config/joi.validate';
import schema from '../utils/validator';

const router = express.Router();

/**
 * @swagger
 * tags:
 *   - name: admin
 *     description: Admin operations
 */

/**
 * @swagger
 * definitions:
 *   Admin:
 *     type: object
 *     properties:
 *       id:
 *         type: integer
 *         description: Unique identifier representing a specific admin
 *         example: 2
*       adminname:
 *         type: string
 *         description: adminname
 *         example: Timilsina
 *       first_name:
 *         type: string
 *         description: first name of the admin
 *         example: Krishna
 *       last_name:
 *         type: string
 *         description: last name of the admin
 *         example: Timilsina
 *       email:
 *         type: string
 *         description: email of the admin
 *         required: true
 *         example: test@gmail.com
 *       password:
 *         type: string
 *         description: password of the admin
 *         required: true
 *         example: "1234"
 *       created:
 *         type: string
 *         format: date-time
 *         description: Admin creation datetime
 *   Error:
 *     type: object
 *     properties:
 *        message:
 *           type: string
 *        error:
 *           type: boolean
 *           default: true
 */

/**
 * @swagger
 * securityDefinitions:
 *   Bearer:
 *     description: |
 *            For accessing the API a valid JWT token must be passed in all the queries in
 *            the 'Authorization' header.
 *
 *
 *            A valid JWT token is generated by the API and returned as answer of a call
 *            to the route /auth/login giving a valid admin & password.
 *
 *
 *            The following syntax must be used in the 'Authorization' header:
 *
 *            Bearer xxxxxx.yyyyyyy.zzzzzz
 *     type: apiKey
 *     name: Authorization
 *     in: header
 *
 */

router.route('/')

/**
 * @swagger
 * /admins:
 *   post:
 *     tags:
 *       - admin
 *     summary: "Create a new admin"
 *     security:
 *        - Bearer: []
 *     operationId: storeAdmin
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: body
 *         in: body
 *         description: Created admin object
 *         required: true
 *         schema:
 *           $ref: "#/definitions/Admin"
 *     responses:
 *       200:
 *         description: OK
 *         schema:
 *           $ref: "#/definitions/Admin"
 *       403:
 *          description: Admin not found
 *          schema:
 *             $ref: '#/definitions/Error'
 */

	.post(validate(schema.storeAdmin), (req, res) => {
		adminCtrl.store(req, res);
	})

/**
     * @swagger
     * /admins:
     *   get:
     *     tags:
     *       - admin
     *     summary: "List all admins"
     *     operationId: findAll
     *     consumes:
     *       - application/json
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: page
     *         in: query
     *         description: Page Number
     *         required: false
     *         schema:
     *           $ref: "#/definitions/Admin"
     *       - name: limit
     *         in: query
     *         description: Number of admins
     *         required: false
     *         schema:
     *           $ref: "#/definitions/Admin"
     *       - name: sort
     *         in: query
     *         description: key for sortby
     *         required: false
     *         schema:
     *           $ref: "#/definitions/Admin"
     *     responses:
     *       200:
     *         description: OK
     *         schema:
     *            type: object
     */

	.get( (req, res) => {
		adminCtrl.findAll(req, res);
	});


router.route('/:id')

/**
 * @swagger
 * /admins/{id}:
 *   get:
 *     tags:
 *       - admin
 *     summary: Find the admin by ID
 *     operationId: findById
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: id
 *         in: path
 *         description: id of admin that needs to be fetched
 *         required: true
 *         type: integer
 *     responses:
 *       200:
 *         description: OK
 *         schema:
 *           $ref: "#/definitions/Admin"
 *       404:
 *          description: Admin not found
 *          schema:
 *             $ref: '#/definitions/Error'
 */

	.get( (req, res) => {
		adminCtrl.findById(req, res);
	})

/**
     * @swagger
     * /admins/{id}:
     *   put:
     *     tags:
     *       - admin
     *     summary: "Update an existing admin by ID"
     *     security:
     *       - Bearer: []
     *     operationId: update
     *     consumes:
     *       - application/json
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: id
     *         in: path
     *         description: id that need to be updated
     *         required: true
     *         type: integer
     *       - name: body
     *         in: body
     *         description: Updated admin object
     *         required: true
     *         schema:
     *           $ref: "#/definitions/Admin"
     *     responses:
     *       200:
     *         description: OK
     *         schema:
     *           $ref: "#/definitions/Admin"
     *       400:
     *         description: Invalid admin
     */

	.put(isAuthenticated, (req, res) => {
		adminCtrl.update(req, res);
	})

/**
     * @swagger
     * /admins/{id}:
     *   delete:
     *     tags:
     *       - admin
     *     summary: Delete the admin by ID
     *     security:
     *       - Bearer: []
     *     operationId: destroy
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: id
     *         in: path
     *         description: id of admin that needs to be deleted
     *         required: true
     *         type: integer
     *     responses:
     *       200:
     *         description: OK
     *       400:
     *          description: "Invalid ID"
     */

	.delete(isAuthenticated, (req, res) => {
		adminCtrl.destroy(req, res);
	});


export default router;