export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const ENTITY_FAILURE = 'ENTITY_FAILURE';
export const ENTITY_CREATE = 'ENTITY_CREATE';
export const ENTITY_UPDATE = 'ENTITY_UPDATE';
export const ENTITY_FETCH = 'ENTITY_FETCH';
export const ENTITY_DELETE = 'ENTITY_DELETE';
export const SELECT_ENTITY_ITEM = 'SELECT_ENTITY_ITEM';
export const CLEAR_ENTITY_LIST = 'CLEAR_ENTITY_LIST';

export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const RESET_EVENT = 'RESET_EVENT';
export const APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE';
export const USERS_INITIALVALUES_UPDATE = 'USERS_INITIALVALUES_UPDATE';
export const UPDATE_VERIFY_STATUS = 'UPDATE_VERIFY_STATUS';
export const SEND_API_REQUEST = 'SEND_API_REQUEST';

// Services Actions 
